[build]
  publish = "build/web"
  command = "flutter build web --release --base-href / --web-renderer canvaskit"

[build.environment]
  # Especifica la versión de Flutter que usas
  FLUTTER_VERSION = "3.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
